dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Controllers/ReturnRequestController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Nop.Core.Domain.Orders;
using Nop.Services.Customers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Orders;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class ReturnRequestController : BaseAdminController
    {
        #region Fields

        private readonly ICustomerActivityService _customerActivityService;
        private readonly ICustomerService _customerService;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly INotificationService _notificationService;
        private readonly IOrderService _orderService;
        private readonly IPermissionService _permissionService;
        private readonly IReturnRequestModelFactory _returnRequestModelFactory;
        private readonly IReturnRequestService _returnRequestService;
        private readonly IWorkflowMessageService _workflowMessageService;

        #endregion Fields

        #region Ctor

        public ReturnRequestController(ICustomerActivityService customerActivityService,
            ICustomerService customerService,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            INotificationService notificationService,
            IOrderService orderService,
            IPermissionService permissionService,
            IReturnRequestModelFactory returnRequestModelFactory,
            IReturnRequestService returnRequestService,
            IWorkflowMessageService workflowMessageService)
        {
            _customerActivityService = customerActivityService;
            _customerService = customerService;
            _localizationService = localizationService;
            _localizedEntityService = localizedEntityService;
            _notificationService = notificationService;
            _orderService = orderService;
            _permissionService = permissionService;
            _returnRequestModelFactory = returnRequestModelFactory;
            _returnRequestService = returnRequestService;
            _workflowMessageService = workflowMessageService;
        }

        #endregion

        #region Utilities

        protected virtual void UpdateLocales(ReturnRequestReason rrr, ReturnRequestReasonModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(rrr,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
            }
        }

        protected virtual void UpdateLocales(ReturnRequestAction rra, ReturnRequestActionModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(rra,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
            }
        }

        #endregion

        #region Methods

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            //prepare model
            var model = _returnRequestModelFactory.PrepareReturnRequestSearchModel(new ReturnRequestSearchModel());

            return View(model);
        }

        [HttpPost]
        public virtual IActionResult List(ReturnRequestSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedDataTablesJson();

            //prepare model
            var model = _returnRequestModelFactory.PrepareReturnRequestListModel(searchModel);

            return Json(model);
        }

        public virtual IActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            //try to get a return request with the specified id
            var returnRequest = _returnRequestService.GetReturnRequestById(id);
            if (returnRequest == null)
                return RedirectToAction("List");

            //prepare model
            var model = _returnRequestModelFactory.PrepareReturnRequestModel(null, returnRequest);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        public virtual IActionResult Edit(ReturnRequestModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            //try to get a return request with the specified id
            var returnRequest = _returnRequestService.GetReturnRequestById(model.Id);
            if (returnRequest == null)
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                returnRequest = model.ToEntity(returnRequest);
                returnRequest.UpdatedOnUtc = DateTime.UtcNow;
                _customerService.UpdateCustomer(returnRequest.Customer);

                //activity log
                _customerActivityService.InsertActivity("EditReturnRequest",
                    string.Format(_localizationService.GetResource("ActivityLog.EditReturnRequest"), returnRequest.Id), returnRequest);

                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.ReturnRequests.Updated"));

                return continueEditing ? RedirectToAction("Edit", new { id = returnRequest.Id }) : RedirectToAction("List");
            }

            //prepare model
            model = _returnRequestModelFactory.PrepareReturnRequestModel(model, returnRequest, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpPost, ActionName("Edit")]
        [FormValueRequired("notify-customer")]
        public virtual IActionResult NotifyCustomer(ReturnRequestModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            //try to get a return request with the specified id
            var returnRequest = _returnRequestService.GetReturnRequestById(model.Id);
            if (returnRequest == null)
                return RedirectToAction("List");

            var orderItem = _orderService.GetOrderItemById(returnRequest.OrderItemId);
            if (orderItem == null)
            {
                _notificationService.ErrorNotification(_localizationService.GetResource("Admin.ReturnRequests.OrderItemDeleted"));
                return RedirectToAction("Edit", new { id = returnRequest.Id });
            }

            var queuedEmailIds = _workflowMessageService.SendReturnRequestStatusChangedCustomerNotification(returnRequest, orderItem, orderItem.Order.CustomerLanguageId);
            if (queuedEmailIds.Any())
                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.ReturnRequests.Notified"));

            return RedirectToAction("Edit", new { id = returnRequest.Id });
        }

        [HttpPost]
        public virtual IActionResult Delete(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            //try to get a return request with the specified id
            var returnRequest = _returnRequestService.GetReturnRequestById(id);
            if (returnRequest == null)
                return RedirectToAction("List");

            _returnRequestService.DeleteReturnRequest(returnRequest);

            //activity log
            _customerActivityService.InsertActivity("DeleteReturnRequest",
                string.Format(_localizationService.GetResource("ActivityLog.DeleteReturnRequest"), returnRequest.Id), returnRequest);

            _notificationService.SuccessNotification(_localizationService.GetResource("Admin.ReturnRequests.Deleted"));

            return RedirectToAction("List");
        }

        #region Return request reasons

        public virtual IActionResult ReturnRequestReasonList()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //select an appropriate panel
            SaveSelectedPanelName("ordersettings-return-request");

            //we just redirect a user to the order settings page
            return RedirectToAction("Order", "Setting");
        }

        [HttpPost]
        public virtual IActionResult ReturnRequestReasonList(ReturnRequestReasonSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedDataTablesJson();

            //prepare model
            var model = _returnRequestModelFactory.PrepareReturnRequestReasonListModel(searchModel);

            return Json(model);
        }

        public virtual IActionResult ReturnRequestReasonCreate()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //prepare model

dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Views/ReturnRequest/Edit.cshtml
@model ReturnRequestModel

@{
    //page title
    ViewBag.Title = T("Admin.ReturnRequests.EditReturnRequestDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Return requests");
}

<form asp-controller="ReturnRequest" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.ReturnRequests.EditReturnRequestDetails")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.ReturnRequests.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="notify-customer" class="btn bg-aqua">
                <i class="fa fa-envelope-o"></i>
                @T("Admin.ReturnRequests.NotifyCustomer")
            </button>
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="returnrequest-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReturnRequestDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="returnrequest-delete" />

dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Views/ReturnRequest/List.cshtml
@model ReturnRequestSearchModel

@{
    //page title
    ViewBag.Title = T("Admin.ReturnRequests").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Return requests");
}

@{
    const string hideSearchBlockAttributeName = "ReturnRequestsPage.HideSearchBlock";
    var hideSearchBlock = genericAttributeService.GetAttribute<bool>(workContext.CurrentCustomer, hideSearchBlockAttributeName);
}

<nop-antiforgery-token />
<div class="content-header clearfix">
    <h1 class="pull-left">
        @T("Admin.ReturnRequests")
    </h1>
    <div class="pull-right">
        &nbsp;
        @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReturnRequestListButtons })
    </div>
</div>
<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default panel-search">
                <div class="panel-body">
                    <div class="row search-row @(!hideSearchBlock ? "opened" : "")" data-hideAttribute="@hideSearchBlockAttributeName">
                        <div class="search-text">@T("Admin.Common.Search")</div>
                        <div class="icon-search"><i class="fa fa-search" aria-hidden="true"></i></div>
                        <div class="icon-collapse"><i class="fa fa-angle-down" aria-hidden="true"></i></div>
                    </div>

                    <div class="search-body @(hideSearchBlock ? "closed" : "")">

                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <nop-label asp-for="StartDate" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-editor asp-for="StartDate" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <nop-label asp-for="EndDate" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-editor asp-for="EndDate" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-7">
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <nop-label asp-for="CustomNumber" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-editor asp-for="CustomNumber" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <nop-label asp-for="ReturnRequestStatusId" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-select asp-for="ReturnRequestStatusId" asp-items="Model.ReturnRequestStatusList" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-7 col-md-offset-5">
                                <button type="button" id="search-returnrequests" class="btn btn-primary btn-search">
                                    <i class="fa fa-search"></i>
                                    @T("Admin.Common.Search")
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-body">
                    <p>
                        @T("Admin.ReturnRequests.Description")
                    </p>
                    @await Html.PartialAsync("Table", new DataTablesModel
                    {
                        Name = "returnrequests-grid",
                        UrlRead = new DataUrl("List", "ReturnRequest", null),
                        SearchButtonId = "search-returnrequests",
                        Length = Model.PageSize,
                        LengthMenu = Model.AvailablePageSizes,
                        Filters = new List<FilterParameter>
                        {
                            new FilterParameter(nameof(Model.StartDate)),
                            new FilterParameter(nameof(Model.EndDate)),
                            new FilterParameter(nameof(Model.CustomNumber)),
                            new FilterParameter(nameof(Model.ReturnRequestStatusId))
                        },
                        ColumnCollection = new List<ColumnProperty>
                        {
                            new ColumnProperty(nameof(ReturnRequestModel.CustomNumber))
                            {
                                Title = T("Admin.ReturnRequests.Fields.CustomNumber").Text,
                                Width = "100"
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.ProductName))
                            {
                                Title = T("Admin.ReturnRequests.Fields.Product").Text,
                                Width = "350",
                                Render = new RenderCustom("renderColumnProductName")
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.Quantity))
                            {
                                Title = T("Admin.ReturnRequests.Fields.Quantity").Text,
                                Width = "100"
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.CustomerId))
                            {
                                Title = T("Admin.ReturnRequests.Fields.Customer").Text,
                                Width = "350",
                                Render = new RenderCustom("renderColumnCustomerInfo")
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.CustomOrderNumber))
                            {
                                Title = T("Admin.ReturnRequests.Fields.CustomOrderNumber").Text,
                                ClassName =  NopColumnClassDefaults.Button,
                                Width = "200",
                                Render = new RenderCustom("renderColumnOrderInfo")
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.ReturnRequestStatusStr))
                            {
                                Title = T("Admin.ReturnRequests.Fields.Status").Text,
                                Width = "200"
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.CreatedOn))
                            {
                                Title = T("Admin.ReturnRequests.Fields.CreatedOn").Text,
                                Width = "100",
                                Render = new RenderDate()
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.Id))
                            {
                                Title = T("Admin.Common.Edit").Text,
                                Width = "100",
                                ClassName =  NopColumnClassDefaults.Button,
                                Render = new RenderButtonEdit(new DataUrl("Edit"))
                            }
                        }
                    })
                    
                    <script>
                        function renderColumnProductName(data, type, row, meta) {
                            if (row.ProductId > 0) {
                                var textRenderer = $.fn.dataTable.render.text().display;
                                var productInfo = '<a href="@Url.Content("~/Admin/Product/Edit/")' + row.ProductId + '">' + textRenderer(row.ProductName) + '</a>';
                                var attributeInfo = '';
                                if (row.AttributeInfo && row.AttributeInfo.length > 0) {
                                    attributeInfo = '<div>' + row.AttributeInfo +'</div>';
                                }
                                return productInfo + attributeInfo;
                            } else {
                                return 'order item is deleted';
                            }
                        }

                        function renderColumnCustomerInfo(data, type, row, meta) {
                            var textRenderer = $.fn.dataTable.render.text().display;
                            return '<a href="@Url.Content("~/Admin/Customer/Edit/")' + row.CustomerId + '">' + textRenderer(row.CustomerInfo) + '</a>';
                        }

                        function renderColumnOrderInfo(data, type, row, meta) {
                            if (row.OrderId > 0) {
                                var textRenderer = $.fn.dataTable.render.text().display;
                                return '<a class="btn btn-default" href="@Url.Content("~/Admin/Order/Edit/")' + row.OrderId + '"><i class="fa fa-eye"></i>' + textRenderer(row.CustomOrderNumber) + ' - @T("Admin.Common.View")</a>';
                            } else {
                                return 'order item is deleted';
                            }
                        }
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Views/ReturnRequest/ReturnRequestActionCreate.cshtml
@model ReturnRequestActionModel

@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Settings.Order.ReturnRequestActions.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Order settings");
}

<form asp-controller="ReturnRequest" asp-action="ReturnRequestActionCreate" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Configuration.Settings.Order.ReturnRequestActions.AddNew")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="ReturnRequestActionList">@T("Admin.Configuration.Settings.Order.ReturnRequestActions.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReturnRequestActionDetailsButtons })
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("_CreateOrUpdate.ReturnRequestAction", Model)
        </div>
    </div>
</form>

dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Views/ReturnRequest/ReturnRequestActionEdit.cshtml
@model ReturnRequestActionModel

@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Settings.Order.ReturnRequestActions.EditDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Order settings");
}


<form asp-controller="ReturnRequest" asp-action="ReturnRequestActionEdit" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Configuration.Settings.Order.ReturnRequestActions.EditDetails") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="ReturnRequestActionList">@T("Admin.Configuration.Settings.Order.ReturnRequestActions.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="returnrequestaction-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReturnRequestActionDetailsButtons, additionalData = Model })
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("_CreateOrUpdate.ReturnRequestAction", Model)
        </div>
    </div>
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="returnrequestaction-delete" asp-action="ReturnRequestActionDelete"/>

dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Views/ReturnRequest/ReturnRequestReasonCreate.cshtml
@model ReturnRequestReasonModel

@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Settings.Order.ReturnRequestReasons.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Order settings");
}


<form asp-controller="ReturnRequest" asp-action="ReturnRequestReasonCreate" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Configuration.Settings.Order.ReturnRequestReasons.AddNew")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="ReturnRequestReasonList">@T("Admin.Configuration.Settings.Order.ReturnRequestReasons.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReturnRequestReasonDetailsButtons })
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("_CreateOrUpdate.ReturnRequestReason", Model)
        </div>
    </div>
</form>

dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Views/ReturnRequest/ReturnRequestReasonEdit.cshtml
@model ReturnRequestReasonModel

@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Settings.Order.ReturnRequestReasons.EditDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Order settings");
}

<form asp-controller="ReturnRequest" asp-action="ReturnRequestReasonEdit" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Configuration.Settings.Order.ReturnRequestReasons.EditDetails") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="ReturnRequestReasonList">@T("Admin.Configuration.Settings.Order.ReturnRequestReasons.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="returnrequestreason-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReturnRequestReasonDetailsButtons, additionalData = Model })
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("_CreateOrUpdate.ReturnRequestReason", Model)
        </div>
    </div>
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="returnrequestreason-delete" asp-action="ReturnRequestReasonDelete"/>

dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Views/ReturnRequest/_CreateOrUpdate.ReturnRequestAction.cshtml
@model ReturnRequestActionModel

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

<div class="panel-group">
    @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReturnRequestActionSettingsTop })
    <div class="panel panel-default">
        <div class="panel-body">
            @(Html.LocalizedEditor<ReturnRequestActionModel, ReturnRequestActionLocalizedModel>("returnrequestaction-localized",
            @<div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="@Model.Locales[item].Name" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="@Model.Locales[item].Name" />
                        <span asp-validation-for="@Model.Locales[item].Name"></span>
                    </div>
                </div>
                <input type="hidden" asp-for="@Model.Locales[item].LanguageId" />
            </div>
    ,
            @<div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="Name" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Name" asp-required="true" />
                        <span asp-validation-for="Name"></span>
                    </div>
                </div>
            </div>
    ))
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="DisplayOrder" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="DisplayOrder" />
                    <span asp-validation-for="DisplayOrder"></span>
                </div>
            </div>
        </div>
    </div>
    @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReturnRequestActionSettingsBottom })
</div>