dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Controllers/GiftCardController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Directory;
using Nop.Core.Domain.Localization;
using Nop.Core.Domain.Orders;
using Nop.Services.Catalog;
using Nop.Services.Directory;
using Nop.Services.Helpers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Orders;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class GiftCardController : BaseAdminController
    {
        #region Fields

        private readonly CurrencySettings _currencySettings;
        private readonly ICurrencyService _currencyService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly IGiftCardModelFactory _giftCardModelFactory;
        private readonly IGiftCardService _giftCardService;
        private readonly ILanguageService _languageService;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly IPriceFormatter _priceFormatter;
        private readonly IWorkflowMessageService _workflowMessageService;
        private readonly LocalizationSettings _localizationSettings;

        #endregion

        #region Ctor

        public GiftCardController(CurrencySettings currencySettings,
            ICurrencyService currencyService,
            ICustomerActivityService customerActivityService,
            IDateTimeHelper dateTimeHelper,
            IGiftCardModelFactory giftCardModelFactory,
            IGiftCardService giftCardService,
            ILanguageService languageService,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            IPriceFormatter priceFormatter,
            IWorkflowMessageService workflowMessageService,
            LocalizationSettings localizationSettings)
        {
            _currencySettings = currencySettings;
            _currencyService = currencyService;
            _customerActivityService = customerActivityService;
            _dateTimeHelper = dateTimeHelper;
            _giftCardModelFactory = giftCardModelFactory;
            _giftCardService = giftCardService;
            _languageService = languageService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _priceFormatter = priceFormatter;
            _workflowMessageService = workflowMessageService;
            _localizationSettings = localizationSettings;
        }

        #endregion

        #region Methods

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageGiftCards))
                return AccessDeniedView();

            //prepare model
            var model = _giftCardModelFactory.PrepareGiftCardSearchModel(new GiftCardSearchModel());

            return View(model);
        }

        [HttpPost]
        public virtual IActionResult GiftCardList(GiftCardSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageGiftCards))
                return AccessDeniedDataTablesJson();

            //prepare model
            var model = _giftCardModelFactory.PrepareGiftCardListModel(searchModel);

            return Json(model);
        }

        public virtual IActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageGiftCards))
                return AccessDeniedView();

            //prepare model
            var model = _giftCardModelFactory.PrepareGiftCardModel(new GiftCardModel(), null);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public virtual IActionResult Create(GiftCardModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageGiftCards))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var giftCard = model.ToEntity<GiftCard>();
                giftCard.CreatedOnUtc = DateTime.UtcNow;
                _giftCardService.InsertGiftCard(giftCard);

                //activity log
                _customerActivityService.InsertActivity("AddNewGiftCard",
                    string.Format(_localizationService.GetResource("ActivityLog.AddNewGiftCard"), giftCard.GiftCardCouponCode), giftCard);

                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.GiftCards.Added"));

                return continueEditing ? RedirectToAction("Edit", new { id = giftCard.Id }) : RedirectToAction("List");
            }

            //prepare model
            model = _giftCardModelFactory.PrepareGiftCardModel(model, null, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        public virtual IActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageGiftCards))
                return AccessDeniedView();

            //try to get a gift card with the specified id
            var giftCard = _giftCardService.GetGiftCardById(id);
            if (giftCard == null)
                return RedirectToAction("List");

            //prepare model
            var model = _giftCardModelFactory.PrepareGiftCardModel(null, giftCard);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        public virtual IActionResult Edit(GiftCardModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageGiftCards))
                return AccessDeniedView();

            //try to get a gift card with the specified id
            var giftCard = _giftCardService.GetGiftCardById(model.Id);
            if (giftCard == null)
                return RedirectToAction("List");

            model.PurchasedWithOrderId = giftCard.PurchasedWithOrderItem != null ? (int?)giftCard.PurchasedWithOrderItem.OrderId : null;
            model.RemainingAmountStr = _priceFormatter.FormatPrice(_giftCardService.GetGiftCardRemainingAmount(giftCard), true, false);
            model.AmountStr = _priceFormatter.FormatPrice(giftCard.Amount, true, false);
            model.CreatedOn = _dateTimeHelper.ConvertToUserTime(giftCard.CreatedOnUtc, DateTimeKind.Utc);
            model.PrimaryStoreCurrencyCode = _currencyService.GetCurrencyById(_currencySettings.PrimaryStoreCurrencyId).CurrencyCode;
            model.PurchasedWithOrderNumber = giftCard.PurchasedWithOrderItem?.Order.CustomOrderNumber;

            if (ModelState.IsValid)
            {
                giftCard = model.ToEntity(giftCard);
                _giftCardService.UpdateGiftCard(giftCard);

                //activity log
                _customerActivityService.InsertActivity("EditGiftCard",
                    string.Format(_localizationService.GetResource("ActivityLog.EditGiftCard"), giftCard.GiftCardCouponCode), giftCard);

                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.GiftCards.Updated"));

                if (!continueEditing)
                    return RedirectToAction("List");

                return RedirectToAction("Edit", new { id = giftCard.Id });
            }

            //prepare model
            model = _giftCardModelFactory.PrepareGiftCardModel(model, giftCard, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpPost]
        public virtual IActionResult GenerateCouponCode()
        {
            return Json(new { CouponCode = _giftCardService.GenerateGiftCardCode() });
        }

        [HttpPost, ActionName("Edit")]
        [FormValueRequired("notifyRecipient")]
        public virtual IActionResult NotifyRecipient(GiftCardModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageGiftCards))
                return AccessDeniedView();

            //try to get a gift card with the specified id
            var giftCard = _giftCardService.GetGiftCardById(model.Id);
            if (giftCard == null)
                return RedirectToAction("List");

            try
            {
                if (!CommonHelper.IsValidEmail(giftCard.RecipientEmail))
                    throw new NopException("Recipient email is not valid");

                if (!CommonHelper.IsValidEmail(giftCard.SenderEmail))
                    throw new NopException("Sender email is not valid");

                var languageId = 0;
                var order = giftCard.PurchasedWithOrderItem?.Order;
                if (order != null)
                {
                    var customerLang = _languageService.GetLanguageById(order.CustomerLanguageId);
                    if (customerLang == null)
                        customerLang = _languageService.GetAllLanguages().FirstOrDefault();
                    if (customerLang != null)
                        languageId = customerLang.Id;
                }
                else
                {

dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Views/GiftCard/Create.cshtml
@model GiftCardModel

@{
    //page title
    ViewBag.Title = T("Admin.GiftCards.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Gift cards");
}

<form asp-controller="GiftCard" asp-action="Create" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.GiftCards.AddNew") 
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.GiftCards.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.GiftCardDetailsButtons })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>

dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Views/GiftCard/Edit.cshtml
@model GiftCardModel

@{
    //page title
    ViewBag.Title = T("Admin.GiftCards.EditGiftCardDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Gift cards");
}

<form asp-controller="GiftCard" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.GiftCards.EditGiftCardDetails")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.GiftCards.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="giftcard-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.GiftCardDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="giftcard-delete" />

dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Views/GiftCard/List.cshtml
@model GiftCardSearchModel

@{
    //page title
    ViewBag.Title = T("Admin.GiftCards").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Gift cards");
}

@{
    const string hideSearchBlockAttributeName = "GiftCardsPage.HideSearchBlock";
    var hideSearchBlock = genericAttributeService.GetAttribute<bool>(workContext.CurrentCustomer, hideSearchBlockAttributeName);
}

<nop-antiforgery-token />
<div class="content-header clearfix">
    <h1 class="pull-left">
        @T("Admin.GiftCards")
    </h1>
    <div class="pull-right">
        <a asp-action="Create" class="btn bg-blue">
            <i class="fa fa-plus-square"></i>
            @T("Admin.Common.AddNew")
        </a>
        @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.GiftCardListButtons })
    </div>
</div>

<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default panel-search">
                <div class="panel-body">
                    <div class="row search-row @(!hideSearchBlock ? "opened" : "")" data-hideAttribute="@hideSearchBlockAttributeName">
                        <div class="search-text">@T("Admin.Common.Search")</div>
                        <div class="icon-search"><i class="fa fa-search" aria-hidden="true"></i></div>
                        <div class="icon-collapse"><i class="fa fa-angle-down" aria-hidden="true"></i></div>
                    </div>

                    <div class="search-body @(hideSearchBlock ? "closed" : "")">

                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <nop-label asp-for="RecipientName" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-editor asp-for="RecipientName" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <nop-label asp-for="ActivatedId" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-select asp-for="ActivatedId" asp-items="Model.ActivatedList" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-7">
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <nop-label asp-for="CouponCode" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-editor asp-for="CouponCode" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-7 col-md-offset-5">
                                <button type="button" id="search-giftcards" class="btn btn-primary btn-search">
                                    <i class="fa fa-search"></i>
                                    @T("Admin.Common.Search")
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-body">
                    @await Html.PartialAsync("Table", new DataTablesModel
                    {
                        Name = "giftcards-grid",
                        UrlRead = new DataUrl("GiftCardList", "GiftCard", null),
                        SearchButtonId = "search-giftcards",
                        Length = Model.PageSize,
                        LengthMenu = Model.AvailablePageSizes,
                        Filters = new List<FilterParameter>
                        {
                            new FilterParameter(nameof(Model.ActivatedId)),
                            new FilterParameter(nameof(Model.CouponCode)),
                            new FilterParameter(nameof(Model.RecipientName))
                        },
                        ColumnCollection = new List<ColumnProperty>
                        {
                            new ColumnProperty(nameof(GiftCardModel.AmountStr))
                            {
                                Title = T("Admin.GiftCards.Fields.Amount").Text
                            },
                            new ColumnProperty(nameof(GiftCardModel.RemainingAmountStr))
                            {
                                Title = T("Admin.GiftCards.Fields.RemainingAmount").Text
                            },
                            new ColumnProperty(nameof(GiftCardModel.GiftCardCouponCode))
                            {
                                Title = T("Admin.GiftCards.Fields.GiftCardCouponCode").Text
                            },
                            new ColumnProperty(nameof(GiftCardModel.RecipientName))
                            {
                                Title = T("Admin.GiftCards.Fields.RecipientName").Text
                            },
                            new ColumnProperty(nameof(GiftCardModel.IsGiftCardActivated))
                            {
                                Title = T("Admin.GiftCards.Fields.IsGiftCardActivated").Text,
                                Width = "200",
                                ClassName =  NopColumnClassDefaults.CenterAll,
                                Render = new RenderBoolean()
                            },
                            new ColumnProperty(nameof(GiftCardModel.CreatedOn))
                            {
                                Title = T("Admin.GiftCards.Fields.CreatedOn").Text,
                                Width = "200",
                                Render = new RenderDate()
                            },
                            new ColumnProperty(nameof(GiftCardModel.Id))
                            {
                                Title = T("Admin.Common.Edit").Text,
                                Width = "100",
                                ClassName =  NopColumnClassDefaults.Button,
                                Render = new RenderButtonEdit(new DataUrl("Edit"))
                            }
                        }
                    })
                </div>
            </div>
        </div>
    </div>
</div>

dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Views/GiftCard/_CreateOrUpdate.History.cshtml
@model GiftCardModel
<div class="panel-body">
    @await Html.PartialAsync("Table", new DataTablesModel
    {
        Name = "usagehistory-grid",
        UrlRead = new DataUrl("UsageHistoryList", "GiftCard", new RouteValueDictionary { [nameof(Model.GiftCardUsageHistorySearchModel.GiftCardId)] = Model.GiftCardUsageHistorySearchModel.GiftCardId }),
        Length = Model.GiftCardUsageHistorySearchModel.PageSize,
        LengthMenu = Model.GiftCardUsageHistorySearchModel.AvailablePageSizes,
        ColumnCollection = new List<ColumnProperty>
        {
            new ColumnProperty(nameof(GiftCardUsageHistoryModel.CreatedOn))
            {
                Title = T("Admin.GiftCards.History.CreatedOn").Text,
                Width = "200",
                Render = new RenderDate()
            },
            new ColumnProperty(nameof(GiftCardUsageHistoryModel.OrderId))
            {
                Title = T("Admin.GiftCards.History.CustomOrderNumber").Text,
                Width = "200",
                ClassName =  NopColumnClassDefaults.Button,
                Render = new RenderCustom("renderColumnOrderNumber")
            },
            new ColumnProperty(nameof(GiftCardUsageHistoryModel.UsedValue))
            {
                Title = T("Admin.GiftCards.History.UsedValue").Text,
                Width = "200"
            }
        }
    })
    <script>
        function renderColumnOrderNumber(data, type, row, meta) {
            var textRenderer = $.fn.dataTable.render.text().display;
            return '<a class="btn btn-default" href="@Url.Content("~/Admin/Order/Edit/")' + row.OrderId + '"><i class="fa fa-eye"></i>' + textRenderer(row.CustomOrderNumber) + ' - @T("Admin.Common.View")</a>';
        }
    </script>
</div>

dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Views/GiftCard/_CreateOrUpdate.Info.cshtml
@using Nop.Core.Domain.Catalog
@using Nop.Services
@model GiftCardModel

<div class="panel-body">
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="GiftCardTypeId"/>
        </div>
        <div class="col-md-9">
            <nop-select asp-for="GiftCardTypeId" asp-items="((GiftCardType) Model.GiftCardTypeId).ToSelectList()" />
            <span asp-validation-for="GiftCardTypeId"></span>
        </div>
    </div>
    @if (Model.PurchasedWithOrderId.HasValue)
    {
        <div class="form-group">
            <div class="col-md-3">
                <nop-label asp-for="PurchasedWithOrderNumber"/>
            </div>
            <div class="col-md-9">
                <a asp-controller="Order" asp-action="Edit" asp-route-id="@Model.PurchasedWithOrderId.Value">@Model.PurchasedWithOrderNumber - @T("Admin.Common.View")</a>
            </div>
        </div>
    }
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="Amount"/>
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="Amount" asp-postfix="@Model.PrimaryStoreCurrencyCode"/>
            <span asp-validation-for="Amount"></span>
        </div>
    </div>
    @if (Model.Id > 0)
    {
        <div class="form-group">
            <div class="col-md-3">
                <nop-label asp-for="RemainingAmountStr"/>
            </div>
            <div class="col-md-9">
                <div class="form-text-row">@Model.RemainingAmountStr</div>
            </div>
        </div>
    }
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="IsGiftCardActivated"/>
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="IsGiftCardActivated"/>
            <span asp-validation-for="IsGiftCardActivated"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="GiftCardCouponCode"/>
        </div>
        <div class="col-md-9">
            <div class="input-group">
                <nop-editor asp-for="GiftCardCouponCode"/>
                <span asp-validation-for="GiftCardCouponCode"></span>
                <div class="input-group-btn">
                    <button type="button" id="generateCouponCode" class="btn btn-info">@T("Admin.GiftCards.Fields.GiftCardCouponCode.Generate")</button>
                    <script>
                        $(document).ready(function() {
                            $('#generateCouponCode').click(function() {
                                var postData = {};

                                addAntiForgeryToken(postData);

                                $.ajax({
                                    cache: false,
                                    type: "POST",
                                    url: "@(Url.Action("GenerateCouponCode", "GiftCard"))",
                                    data: postData,
                                    success: function (data, textStatus, jqXHR) {
                                        $('#@Html.IdFor(model => model.GiftCardCouponCode)').val(data.CouponCode);
                                    },
                                    error: function (jqXHR, textStatus, errorThrown) {
                                        $('#generateCouponCodeFailed-info').text(errorThrown);
                                        $("#generateCouponCodeFailed").click();                                                
                                    }
                                });
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="RecipientName"/>
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="RecipientName"/>
            <span asp-validation-for="RecipientName"></span>
        </div>
    </div>
    <div class="form-group" id="pnlRecipientEmail">
        <div class="col-md-3">
            <nop-label asp-for="RecipientEmail"/>
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="RecipientEmail"/>
            <span asp-validation-for="RecipientEmail"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="SenderName"/>
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="SenderName"/>
            <span asp-validation-for="SenderName"></span>
        </div>
    </div>
    <div class="form-group" id="pnlSenderEmail">
        <div class="col-md-3">
            <nop-label asp-for="SenderEmail"/>
        </div>
        <div class="col-md-9">
            <nop-editor asp-for="SenderEmail"/>
            <span asp-validation-for="SenderEmail"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <nop-label asp-for="Message"/>
        </div>
        <div class="col-md-9">
            <nop-textarea asp-for="Message"/>
            <span asp-validation-for="Message"></span>
        </div>
    </div>
    @if (Model.Id > 0)
    {
        <div class="form-group" id="pnlNotifyRecipient">
            <div class="col-md-3">
                <nop-label asp-for="IsRecipientNotified"/>
            </div>
            <div class="col-md-9">
                <div class="input-group input-group-short">
                    <div class="input-group-text">
                        <div class="form-text-row">@Model.IsRecipientNotified.ToString()</div>
                    </div>
                    <div class="input-group-btn">
                        <button type="submit" name="notifyRecipient" class="btn btn-info">
                            @T("Admin.GiftCards.Fields.IsRecipientNotified.Notify")
                        </button>
                    </div>
                </div>
            </div>
        </div>
    }
    @if (Model.Id > 0)
    {
        <div class="form-group">
            <div class="col-md-3">
                <nop-label asp-for="CreatedOn"/>
            </div>
            <div class="col-md-9">
                <div class="form-text-row">@Model.CreatedOn</div>
            </div>
        </div>
    }
</div>

<nop-alert asp-alert-id="generateCouponCodeFailed" asp-alert-message="@T("Admin.GiftCards.Fields.GiftCardCouponCode.Alert.FailedGenerate")" />

<script>
    $(document).ready(function() {
        $("#@Html.IdFor(model => model.GiftCardTypeId)").change(toggleGiftCardType);
        toggleGiftCardType();
    });

    function toggleGiftCardType() {
        var selectedGiftCardTypeId = $("#@Html.IdFor(model => model.GiftCardTypeId)").val();
        if (selectedGiftCardTypeId == @(((int) GiftCardType.Virtual).ToString())) {
            $('#pnlRecipientEmail').show();
            $('#pnlSenderEmail').show();
            $('#pnlNotifyRecipient').show();
        } else {
            $('#pnlRecipientEmail').hide();
            $('#pnlSenderEmail').hide();
            $('#pnlNotifyRecipient').hide();
        }
    }
</script>

dotnetapp/src/Presentation/Nop.Web/Areas/Admin/Views/GiftCard/_CreateOrUpdate.cshtml
@model GiftCardModel

@inject Nop.Services.Common.IGenericAttributeService genericAttributeService
@inject IWorkContext workContext
@{
    const string hideInfoBlockAttributeName = "GiftCardPage.HideInfoBlock";
    var hideInfoBlock = genericAttributeService.GetAttribute<bool>(workContext.CurrentCustomer, hideInfoBlockAttributeName);

    const string hideUsageHistoryBlockAttributeName = "GiftCardPage.HideUsageHistoryBlock";
    var HideUsageHistoryBlock = genericAttributeService.GetAttribute<bool>(workContext.CurrentCustomer, hideUsageHistoryBlockAttributeName, defaultValue: true);
}

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

<div class="content">
    <div class="form-horizontal">
        <nop-panels id="gift-card-panels">
            <nop-panel asp-name="gift-card-info" asp-icon="fa fa-info" asp-title="@T("Admin.GiftCards.Info")" asp-hide-block-attribute-name="@hideInfoBlockAttributeName" asp-hide="@hideInfoBlock" asp-advanced="false">@await Html.PartialAsync("_CreateOrUpdate.Info", Model)</nop-panel>
            
            @if (Model.Id > 0)
            {
                <nop-panel asp-name="gift-card-usage-history" asp-icon="fa fa-history" asp-title="@T("Admin.GiftCards.History")" asp-hide-block-attribute-name="@hideUsageHistoryBlockAttributeName" asp-hide="@HideUsageHistoryBlock" asp-advanced="false">@await Html.PartialAsync("_CreateOrUpdate.History", Model)</nop-panel>
            }
        
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.GiftCardDetailsBlock, additionalData = Model })
        </nop-panels>
    </div>
</div>